---
- name: Preparing Workstation2
  hosts: localhost
  connection: local
  tasks:
    - block: 
      - name: Remove files (delete files)
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /tmp/teams.deb
        - /tmp/discord.deb
        - /tmp/etc.deb
    - block: 
      - name: Descomentando WaylandEnable
        ansible.builtin.lineinfile:
          path: /etc/gdm3/custom.conf
          regexp: '^#WaylandEnable'
          line: WaylandEnable=false
