---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Enable i386 architecture
      command: dpkg --add-architecture i386

    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
        update_cache: true
      loop:
          - flameshot
          - vim
          - openconnect
          - virtualbox
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg
          - lsb-release
          - transmission
          - wine64
          - wine32 
          - libasound2-plugins:i386 
          - libsdl2-2.0-0:i386 
          - libdbus-1-3:i386 
          - libsqlite3-0:i386


    - block:
      - name: Install Google Key
        become: true
        apt_key: 
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present
      - name: Install Google Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: google-chrome
      - name: Install Google Chrome
        become: true
        apt:
          name: google-chrome-stable

    - block:
      - name: Installing Vagrant 2.3.4
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
          
    - block:
      - name: Install Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      - name: Install VSCode Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
          state: present
          filename: vscode
      - name: Install Visual Studio Code
        become: true
        apt:
          name: code
      - name: Install Virtual Studio Code Extensions
        shell:
          cmd: code --install-extension '{{ item }}' 
        loop: 
          - bbenoist.vagrant
          - hashicorp.terraform
          - 4ops.packer
      
          
    - block: 
      - name: Download Teams
        get_url:
          url: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb 
          dest: /tmp/teams.deb
      - name: Install Teams Studio
        become: true
        apt:
          deb: /tmp/teams.deb

    - block: 
      - name: Download Discord
        get_url:
          url: https://discord.com/api/download?platform=linux&format=deb # direto do site
          dest: /tmp/discord.deb
      - name: Install Discord
        become: true
        apt:
          deb: /tmp/discord.deb


    - block:
      - name: Install ffmpeg
        become: true
        apt:
          name: ffmpeg

      - name: Install obs Ubuntu Repo
        become: true
        apt_repository:
          repo: 'ppa:obsproject/obs-studio'
      
      - name: update the apt package index i.e. apt-get update
        become: true
        apt: update_cache=yes
      
      - name: Install obs
        become: true
        apt:
          name: obs-studio

    - block: 
      - name: Install Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present
      - name: Install Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce
      - name: Install Docker
        become: true
        apt:
          name: docker-ce
      - name: Adding existing user to group Docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes
      - name: Install Docker-Compose
        become: true
        get_url:
          url: 'https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64'
          dest: '/usr/local/bin/docker-compose'
          mode: 755

    - block: 
      - name: Download skype
        get_url:
          url: https://go.skype.com/skypeforlinux-64.deb
          dest: /tmp
      - name: Install skype
        become: true
        apt:
          deb: /tmp/skypeforlinux-64.deb
          
    - block: 
      - name: Downlaod Asbru
        get_url:
          url: https://packagecloud.io/asbru-cm/asbru-cm/packages/linuxmint/tricia/asbru-cm_6.3.2-1_all.deb/download.deb?distro_version_id=211
          dest: ~/Downloads
      - name: Install Asbru
        become: true
        apt:
          deb: /home/anderson/Downloads/asbru-cm_6.3.2-1_all.deb

    - block: 
      - name: Download lutris
        get_url:
          url: https://github.com/lutris/lutris/releases/download/v0.5.12/lutris_0.5.12_all.deb
          dest: /tmp/lutris.deb
      - name: Install lutris
        become: true
        apt:
          deb: /tmp/lutris.deb
    
    - block: 
      - name: Descomentando WaylandEnable
            ansible.builtin.lineinfile:
              path: /etc/gdm3/custom.conf
              regexp: '^#WaylandEnable'
              line: WaylandEnable=false
